<?php

namespace Database\Seeders;

use App\Models\League;
use Illuminate\Database\Seeder;

class LeagueSeeder extends Seeder
{
    public function run(): void
    {
        $leagues = [
            ['name' => 'Premier League', 'country' => 'England'],
            ['name' => 'Championship', 'country' => 'England'],
            ['name' => 'League One', 'country' => 'England'],
            ['name' => 'League Two', 'country' => 'England'],
            ['name' => 'National League', 'country' => 'England'],
            ['name' => 'FA Cup', 'country' => 'England'],
            ['name' => 'EFL Cup', 'country' => 'England'],
            ['name' => 'La Liga', 'country' => 'Spain'],
            ['name' => 'Segunda División', 'country' => 'Spain'],
            ['name' => 'Primera Federación', 'country' => 'Spain'],
            ['name' => 'Copa del Rey', 'country' => 'Spain'],
            ['name' => 'Serie A', 'country' => 'Italy'],
            ['name' => 'Serie B', 'country' => 'Italy'],
            ['name' => 'Serie C', 'country' => 'Italy'],
            ['name' => 'Coppa Italia', 'country' => 'Italy'],
            ['name' => 'Bundesliga', 'country' => 'Germany'],
            ['name' => '2. Bundesliga', 'country' => 'Germany'],
            ['name' => '3. Liga', 'country' => 'Germany'],
            ['name' => 'DFB-Pokal', 'country' => 'Germany'],
            ['name' => 'Ligue 1', 'country' => 'France'],
            ['name' => 'Ligue 2', 'country' => 'France'],
            ['name' => 'Championnat National', 'country' => 'France'],
            ['name' => 'Coupe de France', 'country' => 'France'],
            ['name' => 'Primeira Liga', 'country' => 'Portugal'],
            ['name' => 'Liga Portugal 2', 'country' => 'Portugal'],
            ['name' => 'Liga 3', 'country' => 'Portugal'],
            ['name' => 'Taça de Portugal', 'country' => 'Portugal'],
            ['name' => 'Eredivisie', 'country' => 'Netherlands'],
            ['name' => 'Eerste Divisie', 'country' => 'Netherlands'],
            ['name' => 'Tweede Divisie', 'country' => 'Netherlands'],
            ['name' => 'KNVB Cup', 'country' => 'Netherlands'],
            ['name' => 'Jupiler Pro League', 'country' => 'Belgium'],
            ['name' => 'Challenger Pro League', 'country' => 'Belgium'],
            ['name' => 'Belgian Cup', 'country' => 'Belgium'],
            ['name' => 'Belgian Super Cup', 'country' => 'Belgium'],
            ['name' => 'Scottish Premiership', 'country' => 'Scotland'],
            ['name' => 'Scottish Championship', 'country' => 'Scotland'],
            ['name' => 'Scottish League One', 'country' => 'Scotland'],
            ['name' => 'Scottish Cup', 'country' => 'Scotland'],
            ['name' => 'Süper Lig', 'country' => 'Turkey'],
            ['name' => 'TFF First League', 'country' => 'Turkey'],
            ['name' => 'Turkish Cup', 'country' => 'Turkey'],
            ['name' => 'Super League Greece', 'country' => 'Greece'],
            ['name' => 'Greek Cup', 'country' => 'Greece'],
            ['name' => 'Russian Premier League', 'country' => 'Russia'],
            ['name' => 'Russian Football Cup', 'country' => 'Russia'],
            ['name' => 'Ukrainian Premier League', 'country' => 'Ukraine'],
            ['name' => 'Ukrainian Cup', 'country' => 'Ukraine'],
            ['name' => 'Austrian Bundesliga', 'country' => 'Austria'],
            ['name' => '2. Liga', 'country' => 'Austria'],
            ['name' => 'Austrian Cup', 'country' => 'Austria'],
            ['name' => 'Swiss Super League', 'country' => 'Switzerland'],
            ['name' => 'Challenge League', 'country' => 'Switzerland'],
            ['name' => 'Swiss Cup', 'country' => 'Switzerland'],
            ['name' => 'Danish Superliga', 'country' => 'Denmark'],
            ['name' => 'Danish 1st Division', 'country' => 'Denmark'],
            ['name' => 'Danish Cup', 'country' => 'Denmark'],
            ['name' => 'Allsvenskan', 'country' => 'Sweden'],
            ['name' => 'Superettan', 'country' => 'Sweden'],
            ['name' => 'Swedish Cup', 'country' => 'Sweden'],
            ['name' => 'Eliteserien', 'country' => 'Norway'],
            ['name' => 'OBOS-ligaen', 'country' => 'Norway'],
            ['name' => 'Norwegian Cup', 'country' => 'Norway'],
            ['name' => 'Veikkausliiga', 'country' => 'Finland'],
            ['name' => 'Ykkönen', 'country' => 'Finland'],
            ['name' => 'Ekstraklasa', 'country' => 'Poland'],
            ['name' => 'I liga', 'country' => 'Poland'],
            ['name' => 'Polish Cup', 'country' => 'Poland'],
            ['name' => 'Czech First League', 'country' => 'Czech Republic'],
            ['name' => 'Czech Cup', 'country' => 'Czech Republic'],
            ['name' => 'Nemzeti Bajnokság I', 'country' => 'Hungary'],
            ['name' => 'Hungarian Cup', 'country' => 'Hungary'],
            ['name' => 'Liga I', 'country' => 'Romania'],
            ['name' => 'Cupa României', 'country' => 'Romania'],
            ['name' => 'Serbian SuperLiga', 'country' => 'Serbia'],
            ['name' => 'Serbian Cup', 'country' => 'Serbia'],
            ['name' => 'Prva HNL', 'country' => 'Croatia'],
            ['name' => 'Croatian Cup', 'country' => 'Croatia'],
            ['name' => 'Argentine Primera División', 'country' => 'Argentina'],
            ['name' => 'Copa Argentina', 'country' => 'Argentina'],
            ['name' => 'Campeonato Brasileiro Série A', 'country' => 'Brazil'],
            ['name' => 'Campeonato Brasileiro Série B', 'country' => 'Brazil'],
            ['name' => 'Campeonato Brasileiro Série C', 'country' => 'Brazil'],
            ['name' => 'Copa do Brasil', 'country' => 'Brazil'],
            ['name' => 'Categoría Primera A', 'country' => 'Colombia'],
            ['name' => 'Categoría Primera B', 'country' => 'Colombia'],
            ['name' => 'Copa Colombia', 'country' => 'Colombia'],
            ['name' => 'Chilean Primera División', 'country' => 'Chile'],
            ['name' => 'Copa Chile', 'country' => 'Chile'],
            ['name' => 'Uruguayan Primera División', 'country' => 'Uruguay'],
            ['name' => 'Copa Uruguay', 'country' => 'Uruguay'],
            ['name' => 'Paraguayan Primera División', 'country' => 'Paraguay'],
            ['name' => 'Ecuadorian Serie A', 'country' => 'Ecuador'],
            ['name' => 'Peruvian Liga 1', 'country' => 'Peru'],
            ['name' => 'Bolivian Primera División', 'country' => 'Bolivia'],
            ['name' => 'Mexican Liga MX', 'country' => 'Mexico'],
            ['name' => 'Campeones Cup', 'country' => 'CONCACAF'],
            ['name' => 'USL Championship', 'country' => 'USA/Canada'],
            ['name' => 'Indian Super League', 'country' => 'India'],
            ['name' => 'I-League', 'country' => 'India'],
            ['name' => 'Saudi Pro League', 'country' => 'Saudi Arabia'],
            ['name' => 'King Cup', 'country' => 'Saudi Arabia'],
            ['name' => 'Qatar Stars League', 'country' => 'Qatar'],
            ['name' => 'UAE Pro League', 'country' => 'United Arab Emirates'],
            ['name' => 'Iran Pro League', 'country' => 'Iran'],
            ['name' => 'J2 League', 'country' => 'Japan'],
            ['name' => 'K League 2', 'country' => 'South Korea'],
            ['name' => 'China League One', 'country' => 'China'],
            ['name' => 'Botola Pro', 'country' => 'Morocco'],
            ['name' => 'Tunisian Ligue Professionnelle 1', 'country' => 'Tunisia'],
            ['name' => 'Algerian Ligue Professionnelle 1', 'country' => 'Algeria'],
            ['name' => 'Nigerian Professional Football League', 'country' => 'Nigeria'],
            ['name' => 'Ghana Premier League', 'country' => 'Ghana'],
            ['name' => 'Kenyan Premier League', 'country' => 'Kenya'],
            ['name' => 'CAF Champions League', 'country' => 'Africa'],
            ['name' => 'CAF Confederation Cup', 'country' => 'Africa'],
            ['name' => 'Copa Libertadores', 'country' => 'South America'],
            ['name' => 'Copa Sudamericana', 'country' => 'South America'],
            ['name' => 'Recopa Sudamericana', 'country' => 'South America'],
            ['name' => 'UEFA Champions League', 'country' => 'Europe'],
            ['name' => 'UEFA Europa League', 'country' => 'Europe'],
            ['name' => 'UEFA Europa Conference League', 'country' => 'Europe'],
            ['name' => 'UEFA Super Cup', 'country' => 'Europe'],
            ['name' => 'FIFA Club World Cup', 'country' => 'International'],
        ];

        foreach ($leagues as $league) {
            League::updateOrCreate(
                ['name' => $league['name']],
                [
                    'country' => $league['country'],
                    'logo' => null,
                    'is_active' => true,
                ]
            );
        }
    }
}
